apiVersion: v1
kind: ServiceAccount
metadata:
  name: koolna-cache
  namespace: koolna-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: koolna-cache
  namespace: koolna-system
rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "create", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: koolna-cache
  namespace: koolna-system
subjects:
  - kind: ServiceAccount
    name: koolna-cache
    namespace: koolna-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: koolna-cache
