apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: koolna-cache-data
  namespace: koolna-system
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: koolna-cache-ssl
  namespace: koolna-system
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Mi
