services:
  postgres:
    image: postgres:18@sha256:69e8582b781cb44fa4557b98ed586fe68361e320d9b12f9707494335634f4f3d
    environment:
      POSTGRES_DB: clara
      POSTGRES_USER: clara
      POSTGRES_PASSWORD: clara
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:8-alpine@sha256:2afba59292f25f5d1af200496db41bea2c6c816b059f57ae74703a50a03a27d0
    ports:
      - "6379:6379"

volumes:
  pgdata:
