services:
  postgres:
    image: postgres:18@sha256:86c951e05bf56c93d95d397747fb8820ac76cc3bedb78f43abd83eedbe3666ae
    environment:
      POSTGRES_DB: clara
      POSTGRES_USER: clara
      POSTGRES_PASSWORD: clara
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:8-alpine@sha256:bd999b5cfee25fb24b8320a31fddbd69f462df44c8138c66e369582937beebc0
    ports:
      - "6379:6379"

volumes:
  pgdata:
