"""initial

Revision ID: c221f062fcc9
Revises: 
Create Date: 2026-02-18 01:36:26.130938

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c221f062fcc9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Create users and vaults without cross-FKs first (circular dependency)
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('locale', sa.String(length=10), nullable=False),
    sa.Column('timezone', sa.String(length=50), nullable=False),
    sa.Column('default_vault_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('vaults',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('owner_user_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], name=op.f('fk_vaults_owner_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vaults'))
    )
    # Add deferred FK from users -> vaults (after both tables exist)
    op.create_foreign_key(op.f('fk_users_default_vault_id_vaults'), 'users', 'vaults', ['default_vault_id'], ['id'])
    op.create_table('activity_types',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('icon', sa.String(length=50), nullable=False),
    sa.Column('color', sa.String(length=7), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('vault_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['vault_id'], ['vaults.id'], name=op.f('fk_activity_types_vault_id_vaults')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_activity_types'))
    )
    op.create_index(op.f('ix_activity_types_vault_id'), 'activity_types', ['vault_id'], unique=False)
    op.create_table('custom_field_definitions',
    sa.Column('scope', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('data_type', sa.String(length=50), nullable=False),
    sa.Column('config_json', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('vault_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['vault_id'], ['vaults.id'], name=op.f('fk_custom_field_definitions_vault_id_vaults')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_custom_field_definitions'))
    )
    op.create_index(op.f('ix_custom_field_definitions_vault_id'), 'custom_field_definitions', ['vault_id'], unique=False)
    op.create_table('files',
    sa.Column('uploader_id', sa.Uuid(), nullable=False),
    sa.Column('storage_key', sa.String(length=1000), nullable=False),
    sa.Column('filename', sa.String(length=500), nullable=False),
    sa.Column('mime_type', sa.String(length=200), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('vault_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['uploader_id'], ['users.id'], name=op.f('fk_files_uploader_id_users')),
    sa.ForeignKeyConstraint(['vault_id'], ['vaults.id'], name=op.f('fk_files_vault_id_vaults')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_files'))
    )
    op.create_index(op.f('ix_files_vault_id'), 'files', ['vault_id'], unique=False)
    op.create_table('journal_entries',
    sa.Column('entry_date', sa.Date(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('body_markdown', sa.Text(), nullable=False),
    sa.Column('mood', sa.Integer(), nullable=True),
    sa.Column('created_by_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('vault_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_journal_entries_created_by_id_users')),
    sa.ForeignKeyConstraint(['vault_id'], ['vaults.id'], name=op.f('fk_journal_entries_vault_id_vaults')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_journal_entries'))
    )
    op.create_index(op.f('ix_journal_entries_vault_id'), 'journal_entries', ['vault_id'], unique=False)
    op.create_table('personal_access_tokens',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('token_prefix', sa.String(length=12), nullable=False),
    sa.Column('token_hash', sa.Text(), nullable=False),
    sa.Column('scopes', sa.Text(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_personal_access_tokens_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_personal_access_tokens'))
    )
    op.create_table('recovery_codes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('code_hash', sa.String(length=255), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_recovery_codes_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_recovery_codes'))
    )
    op.create_table('relationship_types',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('inverse_type_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('vault_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['inverse_type_id'], ['relationship_types.id'], name=op.f('fk_relationship_types_inverse_type_id_relationship_types')),
    sa.ForeignKeyConstraint(['vault_id'], ['vaults.id'], name=op.f('fk_relationship_types_vault_id_vaults')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_relationship_types'))
    )
    op.create_index(op.f('ix_relationship_types_vault_id'), 'relationship_types', ['vault_id'], unique=False)
    op.create_table('tags',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('color', sa.String(length=7), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('vault_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['vault_id'], ['vaults.id'], name=op.f('fk_tags_vault_id_vaults')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tags'))
    )
    op.create_index(op.f('ix_tags_vault_id'), 'tags', ['vault_id'], unique=False)
    op.create_table('templates',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('vault_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['vault_id'], ['vaults.id'], name=op.f('fk_templates_vault_id_vaults')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_templates'))
    )
    op.create_index(op.f('ix_templates_vault_id'), 'templates', ['vault_id'], unique=False)
    op.create_table('totp_devices',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('secret', sa.String(length=255), nullable=False),
    sa.Column('confirmed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_totp_devices_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_totp_devices'))
    )
    op.create_table('vault_memberships',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('vault_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_vault_memberships_user_id_users')),
    sa.ForeignKeyConstraint(['vault_id'], ['vaults.id'], name=op.f('fk_vault_memberships_vault_id_vaults')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vault_memberships'))
    )
    op.create_table('vault_settings',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('vault_id', sa.Uuid(), nullable=False),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('date_format', sa.String(length=20), nullable=False),
    sa.Column('time_format', sa.String(length=5), nullable=False),
    sa.Column('timezone', sa.String(length=50), nullable=False),
    sa.Column('feature_flags', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['vault_id'], ['vaults.id'], name=op.f('fk_vault_settings_vault_id_vaults')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vault_settings')),
    sa.UniqueConstraint('vault_id', name=op.f('uq_vault_settings_vault_id'))
    )
    op.create_table('activities',
    sa.Column('activity_type_id', sa.Uuid(), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('happened_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('location', sa.String(length=500), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('vault_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['activity_type_id'], ['activity_types.id'], name=op.f('fk_activities_activity_type_id_activity_types')),
    sa.ForeignKeyConstraint(['vault_id'], ['vaults.id'], name=op.f('fk_activities_vault_id_vaults')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_activities'))
    )
    op.create_index(op.f('ix_activities_vault_id'), 'activities', ['vault_id'], unique=False)
    op.create_table('contacts',
    sa.Column('first_name', sa.String(length=255), nullable=False),
    sa.Column('last_name', sa.String(length=255), nullable=False),
    sa.Column('nickname', sa.String(length=255), nullable=True),
    sa.Column('birthdate', sa.Date(), nullable=True),
    sa.Column('gender', sa.String(length=50), nullable=True),
    sa.Column('pronouns', sa.String(length=100), nullable=True),
    sa.Column('notes_summary', sa.Text(), nullable=True),
    sa.Column('favorite', sa.Boolean(), nullable=False),
    sa.Column('photo_file_id', sa.Uuid(), nullable=True),
    sa.Column('template_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('vault_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['template_id'], ['templates.id'], name=op.f('fk_contacts_template_id_templates')),
    sa.ForeignKeyConstraint(['vault_id'], ['vaults.id'], name=op.f('fk_contacts_vault_id_vaults')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_contacts'))
    )
    op.create_index(op.f('ix_contacts_vault_id'), 'contacts', ['vault_id'], unique=False)
    op.create_table('custom_field_values',
    sa.Column('definition_id', sa.Uuid(), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=False),
    sa.Column('value_json', sa.Text(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('vault_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['definition_id'], ['custom_field_definitions.id'], name=op.f('fk_custom_field_values_definition_id_custom_field_definitions')),
    sa.ForeignKeyConstraint(['vault_id'], ['vaults.id'], name=op.f('fk_custom_field_values_vault_id_vaults')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_custom_field_values'))
    )
    op.create_index(op.f('ix_custom_field_values_vault_id'), 'custom_field_values', ['vault_id'], unique=False)
    op.create_table('file_links',
    sa.Column('file_id', sa.Uuid(), nullable=False),
    sa.Column('target_type', sa.String(length=50), nullable=False),
    sa.Column('target_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('vault_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], name=op.f('fk_file_links_file_id_files')),
    sa.ForeignKeyConstraint(['vault_id'], ['vaults.id'], name=op.f('fk_file_links_vault_id_vaults')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_file_links'))
    )
    op.create_index(op.f('ix_file_links_vault_id'), 'file_links', ['vault_id'], unique=False)
    op.create_table('template_pages',
    sa.Column('template_id', sa.Uuid(), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('vault_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['template_id'], ['templates.id'], name=op.f('fk_template_pages_template_id_templates')),
    sa.ForeignKeyConstraint(['vault_id'], ['vaults.id'], name=op.f('fk_template_pages_vault_id_vaults')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_template_pages'))
    )
    op.create_index(op.f('ix_template_pages_vault_id'), 'template_pages', ['vault_id'], unique=False)
    op.create_table('activity_participants',
    sa.Column('activity_id', sa.Uuid(), nullable=False),
    sa.Column('contact_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.String(length=100), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('vault_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['activity_id'], ['activities.id'], name=op.f('fk_activity_participants_activity_id_activities')),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], name=op.f('fk_activity_participants_contact_id_contacts')),
    sa.ForeignKeyConstraint(['vault_id'], ['vaults.id'], name=op.f('fk_activity_participants_vault_id_vaults')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_activity_participants'))
    )
    op.create_index(op.f('ix_activity_participants_vault_id'), 'activity_participants', ['vault_id'], unique=False)
    op.create_table('addresses',
    sa.Column('contact_id', sa.Uuid(), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=False),
    sa.Column('line1', sa.String(length=500), nullable=False),
    sa.Column('line2', sa.String(length=500), nullable=True),
    sa.Column('city', sa.String(length=255), nullable=False),
    sa.Column('postal_code', sa.String(length=50), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('geo_location', sa.String(length=50), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('vault_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], name=op.f('fk_addresses_contact_id_contacts')),
    sa.ForeignKeyConstraint(['vault_id'], ['vaults.id'], name=op.f('fk_addresses_vault_id_vaults')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_addresses'))
    )
    op.create_index(op.f('ix_addresses_vault_id'), 'addresses', ['vault_id'], unique=False)
    op.create_table('contact_methods',
    sa.Column('contact_id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=False),
    sa.Column('value', sa.String(length=500), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('vault_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], name=op.f('fk_contact_methods_contact_id_contacts')),
    sa.ForeignKeyConstraint(['vault_id'], ['vaults.id'], name=op.f('fk_contact_methods_vault_id_vaults')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_contact_methods'))
    )
    op.create_index(op.f('ix_contact_methods_vault_id'), 'contact_methods', ['vault_id'], unique=False)
    op.create_table('contact_relationships',
    sa.Column('contact_id', sa.Uuid(), nullable=False),
    sa.Column('other_contact_id', sa.Uuid(), nullable=False),
    sa.Column('relationship_type_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('vault_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], name=op.f('fk_contact_relationships_contact_id_contacts')),
    sa.ForeignKeyConstraint(['other_contact_id'], ['contacts.id'], name=op.f('fk_contact_relationships_other_contact_id_contacts')),
    sa.ForeignKeyConstraint(['relationship_type_id'], ['relationship_types.id'], name=op.f('fk_contact_relationships_relationship_type_id_relationship_types')),
    sa.ForeignKeyConstraint(['vault_id'], ['vaults.id'], name=op.f('fk_contact_relationships_vault_id_vaults')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_contact_relationships'))
    )
    op.create_index(op.f('ix_contact_relationships_vault_id'), 'contact_relationships', ['vault_id'], unique=False)
    op.create_table('contact_tags',
    sa.Column('contact_id', sa.Uuid(), nullable=False),
    sa.Column('tag_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], name=op.f('fk_contact_tags_contact_id_contacts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], name=op.f('fk_contact_tags_tag_id_tags'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('contact_id', 'tag_id', name=op.f('pk_contact_tags'))
    )
    op.create_table('debts',
    sa.Column('contact_id', sa.Uuid(), nullable=False),
    sa.Column('direction', sa.String(length=20), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('settled', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('vault_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], name=op.f('fk_debts_contact_id_contacts')),
    sa.ForeignKeyConstraint(['vault_id'], ['vaults.id'], name=op.f('fk_debts_vault_id_vaults')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_debts'))
    )
    op.create_index(op.f('ix_debts_vault_id'), 'debts', ['vault_id'], unique=False)
    op.create_table('gifts',
    sa.Column('contact_id', sa.Uuid(), nullable=False),
    sa.Column('direction', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('link', sa.String(length=2000), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('vault_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], name=op.f('fk_gifts_contact_id_contacts')),
    sa.ForeignKeyConstraint(['vault_id'], ['vaults.id'], name=op.f('fk_gifts_vault_id_vaults')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_gifts'))
    )
    op.create_index(op.f('ix_gifts_vault_id'), 'gifts', ['vault_id'], unique=False)
    op.create_table('journal_entry_contacts',
    sa.Column('journal_entry_id', sa.Uuid(), nullable=False),
    sa.Column('contact_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('vault_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], name=op.f('fk_journal_entry_contacts_contact_id_contacts')),
    sa.ForeignKeyConstraint(['journal_entry_id'], ['journal_entries.id'], name=op.f('fk_journal_entry_contacts_journal_entry_id_journal_entries')),
    sa.ForeignKeyConstraint(['vault_id'], ['vaults.id'], name=op.f('fk_journal_entry_contacts_vault_id_vaults')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_journal_entry_contacts'))
    )
    op.create_index(op.f('ix_journal_entry_contacts_vault_id'), 'journal_entry_contacts', ['vault_id'], unique=False)
    op.create_table('notes',
    sa.Column('contact_id', sa.Uuid(), nullable=True),
    sa.Column('activity_id', sa.Uuid(), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('body_markdown', sa.Text(), nullable=False),
    sa.Column('created_by_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('vault_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['activity_id'], ['activities.id'], name=op.f('fk_notes_activity_id_activities')),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], name=op.f('fk_notes_contact_id_contacts')),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_notes_created_by_id_users')),
    sa.ForeignKeyConstraint(['vault_id'], ['vaults.id'], name=op.f('fk_notes_vault_id_vaults')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notes'))
    )
    op.create_index(op.f('ix_notes_vault_id'), 'notes', ['vault_id'], unique=False)
    op.create_table('pets',
    sa.Column('contact_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('species', sa.String(length=100), nullable=False),
    sa.Column('birthdate', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('vault_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], name=op.f('fk_pets_contact_id_contacts')),
    sa.ForeignKeyConstraint(['vault_id'], ['vaults.id'], name=op.f('fk_pets_vault_id_vaults')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pets'))
    )
    op.create_index(op.f('ix_pets_vault_id'), 'pets', ['vault_id'], unique=False)
    op.create_table('reminders',
    sa.Column('contact_id', sa.Uuid(), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('next_expected_date', sa.Date(), nullable=False),
    sa.Column('frequency_type', sa.String(length=20), nullable=False),
    sa.Column('frequency_number', sa.Integer(), nullable=False),
    sa.Column('last_triggered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('vault_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], name=op.f('fk_reminders_contact_id_contacts')),
    sa.ForeignKeyConstraint(['vault_id'], ['vaults.id'], name=op.f('fk_reminders_vault_id_vaults')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reminders'))
    )
    op.create_index(op.f('ix_reminders_vault_id'), 'reminders', ['vault_id'], unique=False)
    op.create_table('stay_in_touch_configs',
    sa.Column('contact_id', sa.Uuid(), nullable=False),
    sa.Column('target_interval_days', sa.Integer(), nullable=False),
    sa.Column('last_contacted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('vault_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], name=op.f('fk_stay_in_touch_configs_contact_id_contacts')),
    sa.ForeignKeyConstraint(['vault_id'], ['vaults.id'], name=op.f('fk_stay_in_touch_configs_vault_id_vaults')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stay_in_touch_configs')),
    sa.UniqueConstraint('contact_id', name=op.f('uq_stay_in_touch_configs_contact_id'))
    )
    op.create_index(op.f('ix_stay_in_touch_configs_vault_id'), 'stay_in_touch_configs', ['vault_id'], unique=False)
    op.create_table('tasks',
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('contact_id', sa.Uuid(), nullable=True),
    sa.Column('activity_id', sa.Uuid(), nullable=True),
    sa.Column('created_by_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('vault_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['activity_id'], ['activities.id'], name=op.f('fk_tasks_activity_id_activities')),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], name=op.f('fk_tasks_contact_id_contacts')),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_tasks_created_by_id_users')),
    sa.ForeignKeyConstraint(['vault_id'], ['vaults.id'], name=op.f('fk_tasks_vault_id_vaults')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tasks'))
    )
    op.create_index(op.f('ix_tasks_vault_id'), 'tasks', ['vault_id'], unique=False)
    op.create_table('template_modules',
    sa.Column('page_id', sa.Uuid(), nullable=False),
    sa.Column('module_type', sa.String(length=100), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('config_json', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('vault_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['page_id'], ['template_pages.id'], name=op.f('fk_template_modules_page_id_template_pages')),
    sa.ForeignKeyConstraint(['vault_id'], ['vaults.id'], name=op.f('fk_template_modules_vault_id_vaults')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_template_modules'))
    )
    op.create_index(op.f('ix_template_modules_vault_id'), 'template_modules', ['vault_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_template_modules_vault_id'), table_name='template_modules')
    op.drop_table('template_modules')
    op.drop_index(op.f('ix_tasks_vault_id'), table_name='tasks')
    op.drop_table('tasks')
    op.drop_index(op.f('ix_stay_in_touch_configs_vault_id'), table_name='stay_in_touch_configs')
    op.drop_table('stay_in_touch_configs')
    op.drop_index(op.f('ix_reminders_vault_id'), table_name='reminders')
    op.drop_table('reminders')
    op.drop_index(op.f('ix_pets_vault_id'), table_name='pets')
    op.drop_table('pets')
    op.drop_index(op.f('ix_notes_vault_id'), table_name='notes')
    op.drop_table('notes')
    op.drop_index(op.f('ix_journal_entry_contacts_vault_id'), table_name='journal_entry_contacts')
    op.drop_table('journal_entry_contacts')
    op.drop_index(op.f('ix_gifts_vault_id'), table_name='gifts')
    op.drop_table('gifts')
    op.drop_index(op.f('ix_debts_vault_id'), table_name='debts')
    op.drop_table('debts')
    op.drop_table('contact_tags')
    op.drop_index(op.f('ix_contact_relationships_vault_id'), table_name='contact_relationships')
    op.drop_table('contact_relationships')
    op.drop_index(op.f('ix_contact_methods_vault_id'), table_name='contact_methods')
    op.drop_table('contact_methods')
    op.drop_index(op.f('ix_addresses_vault_id'), table_name='addresses')
    op.drop_table('addresses')
    op.drop_index(op.f('ix_activity_participants_vault_id'), table_name='activity_participants')
    op.drop_table('activity_participants')
    op.drop_index(op.f('ix_template_pages_vault_id'), table_name='template_pages')
    op.drop_table('template_pages')
    op.drop_index(op.f('ix_file_links_vault_id'), table_name='file_links')
    op.drop_table('file_links')
    op.drop_index(op.f('ix_custom_field_values_vault_id'), table_name='custom_field_values')
    op.drop_table('custom_field_values')
    op.drop_index(op.f('ix_contacts_vault_id'), table_name='contacts')
    op.drop_table('contacts')
    op.drop_index(op.f('ix_activities_vault_id'), table_name='activities')
    op.drop_table('activities')
    op.drop_table('vault_settings')
    op.drop_table('vault_memberships')
    op.drop_table('totp_devices')
    op.drop_index(op.f('ix_templates_vault_id'), table_name='templates')
    op.drop_table('templates')
    op.drop_index(op.f('ix_tags_vault_id'), table_name='tags')
    op.drop_table('tags')
    op.drop_index(op.f('ix_relationship_types_vault_id'), table_name='relationship_types')
    op.drop_table('relationship_types')
    op.drop_table('recovery_codes')
    op.drop_table('personal_access_tokens')
    op.drop_index(op.f('ix_journal_entries_vault_id'), table_name='journal_entries')
    op.drop_table('journal_entries')
    op.drop_index(op.f('ix_files_vault_id'), table_name='files')
    op.drop_table('files')
    op.drop_index(op.f('ix_custom_field_definitions_vault_id'), table_name='custom_field_definitions')
    op.drop_table('custom_field_definitions')
    op.drop_index(op.f('ix_activity_types_vault_id'), table_name='activity_types')
    op.drop_table('activity_types')
    op.drop_constraint(op.f('fk_users_default_vault_id_vaults'), 'users', type_='foreignkey')
    op.drop_table('vaults')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
